language: php

php:
  - 7.0

services:
    - mysql

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install
    - bin/console doctrine:database:create
    - bin/console doctrine:schema:update --force
    - phpunit -c phpunit.xml.dist
