language: php

php:
  - 7.0
  - hhvm

services:
    - mysql

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - app/console doctrine:database:create --env=test --no-interaction --quiet
